[build]
  command = "node -v && npm ci && npm run build -- --debug && echo '--- ls dist ---' && ls -la dist"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

