[build]
  command = "node -v && npm ci && npm run build -- --debug && echo '--- ls dist ---' && ls -la dist"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# NEW: Tell Netlify where your serverless functions are and how to bundle them
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
