[build]
command = "npm ci --no-audit --no-fund && npm run build"
publish = "dist"


[functions]
directory = "netlify/functions"
node_bundler = "esbuild"


[dev]
framework = "vite"
# `netlify dev` serves the site on 8888 and proxies functions at /.netlify/functions/*
targetPort = 5173


[[redirects]]
from = "/*"
to = "/index.html"
status = 200