// vite.config.mjs
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa' // 👈 NEW: Import the PWA plugin

export default defineConfig({
  plugins: [
    react(),
    // 👇 NEW: Vite PWA Plugin Configuration
    VitePWA({
      registerType: 'autoUpdate',
      // Include assets copied from public folder
      includeAssets: ['favicon.ico', 'icons/*.png', 'manifest.webmanifest'], 
      
      // Configuration for the PWA Manifest
      manifest: {
        name: 'LeaderReps',
        short_name: 'Reps',
        description: 'The leadership development tool for consistent practice.',
        theme_color: '#0056b3',
        icons: [
          {
            src: 'icons/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'icons/icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
        ],
      },
      
      // Workbox configuration for aggressive caching and offline support
      workbox: {
        // Cache all static assets generated by the build
        globPatterns: ['**/*.{js,css,html,ico,png,svg,webmanifest}'],
        
        // Strategy for handling API/external requests (e.g., Firebase/Firestore)
        runtimeCaching: [
          {
            // Caches requests to the Firebase/Google APIs
            urlPattern: ({ url }) => url.origin === 'https://firestore.googleapis.com',
            handler: 'NetworkFirst',
            options: {
              cacheName: 'api-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24, // 24 hours
              },
            },
          },
        ],
      },
    }),
    // 👆 END PWA Plugin Configuration
  ],
  
  resolve: { dedupe: ['react', 'react-dom'] },

  // Build settings retained from your original file
  build: {
    outDir: 'dist', 
    emptyOutDir: true,
    sourcemap: true 
  },

  // Dev / preview niceties retained from your original file
  server: { port: 5173, open: true },
  preview: { port: 4173 }
})